--Amey Ruikar
--USCID 1903-4834-23


DROP index REGIONTABLEINDEX;
DROP index PONDTABLEINDEX;
DROP index AMBULANCETABLEINDEX;
DROP index LIONTABLEINDEX;

DELETE from  user_sdo_geom_metadata where TABLE_NAME = 'LIONTABLE';
DELETE from  user_sdo_geom_metadata where TABLE_NAME = 'AMBULANCETABLE';
DELETE from  user_sdo_geom_metadata where TABLE_NAME = 'PONDTABLE';
DELETE from  user_sdo_geom_metadata where TABLE_NAME = 'REGIONTABLE';

DROP TABLE AMBULANCETABLE;
DROP TABLE PONDTABLE;
DROP TABLE REGIONTABLE;
DROP TABLE LIONTABLE;